import type { CollectionConfig } from 'payload'

import { authenticated } from '../access/authenticated'
import { canAccessCollection } from '../access/isAgentStarter'
import encryptionHooks from '@/hooks/encryptionHook'

export const Bookings: CollectionConfig = {
  slug: 'bookings',
  labels: {
    singular: { en: 'Booking', th: 'ใบจอง' },
    plural: { en: 'All Bookings', th: 'ใบจองทั้งหมด' },
  },
  access: {
    create: authenticated,
    delete: canAccessCollection('bookings', 'delete'),
    read: canAccessCollection('bookings', 'update'),
    update: canAccessCollection('bookings', 'update'),
  },
  admin: {
    useAsTitle: 'pnrCode',
    defaultColumns: [
      'pnrCode',
      'tourCode',
      'firstName',
      'lastName',
      'totalAmount',
      'status',
      'createdAt',
    ],
    description: { en: 'Tour booking data from website', th: 'ข้อมูลการจองทัวร์จากหน้าเว็บ' },
    group: { en: 'Tours', th: 'ทัวร์' },
  },
  fields: [
    // ════════════════════════════════════════════════════════════
    // 1. ข้อมูลพื้นฐานของการจอง (Booking Info)
    // ════════════════════════════════════════════════════════════
    {
      name: 'pnrCode',
      type: 'text',
      required: true,
      unique: true,
      label: { en: 'Booking Code (PNR)', th: 'รหัสจอง (PNR)' },
      admin: {
        readOnly: true,
        description: { en: 'Auto-generated by system', th: 'สร้างอัตโนมัติจากระบบ' },
      },
    },
    {
      name: 'status',
      type: 'select',
      label: { en: 'Status', th: 'สถานะ' },
      defaultValue: 'pending',
      options: [
        { label: { en: 'Pending', th: 'รอติดต่อกลับ' }, value: 'pending' },
        { label: { en: 'Follow Up', th: 'กำลังดำเนินการ' }, value: 'followup' },
        { label: { en: 'Waitlist', th: 'รอคิว' }, value: 'waitlist' },
        { label: { en: 'Confirmed', th: 'ยืนยันการจอง' }, value: 'confirmed' },
        { label: { en: 'Cancelled', th: 'ยกเลิก' }, value: 'cancelled' },
      ],
    },
    {
      name: 'bookingSource',
      type: 'select',
      label: { en: 'Booking Source', th: 'ช่องทางการจอง' },
      defaultValue: 'website',
      options: [
        { label: { en: 'Website', th: 'เว็บไซต์' }, value: 'website' },
        { label: { en: 'Manual Entry', th: 'กรอกมือ (Admin)' }, value: 'manual' },
      ],
      admin: {
        position: 'sidebar',
        description: {
          en: 'How this booking was created',
          th: 'วิธีที่การจองนี้ถูกสร้าง',
        },
      },
    },

    // ════════════════════════════════════════════════════════════
    // 2. รายละเอียดทัวร์ — Tour Snapshot Data
    // ════════════════════════════════════════════════════════════
    {
      type: 'collapsible',
      label: { en: '📋 Tour Snapshot Data', th: '📋 ข้อมูลทัวร์ (Snapshot)' },
      admin: {
        description: {
          en: 'Tour data at the time of booking (snapshot)',
          th: 'ข้อมูลทัวร์ ณ วันที่จอง (Snapshot — ไม่เปลี่ยนตามทัวร์ต้นทาง)',
        },
      },
      fields: [
        {
          name: 'tourTitle',
          type: 'text',
          label: { en: 'Tour Title', th: 'ชื่อทัวร์' },
        },
        {
          type: 'row',
          fields: [
            {
              name: 'tourCode',
              type: 'text',
              label: { en: 'Tour Code', th: 'รหัสทัวร์' },
              admin: { width: '33%' },
            },
            {
              name: 'countryName',
              type: 'text',
              label: { en: 'Country', th: 'ประเทศ' },
              admin: { width: '33%' },
            },
            {
              name: 'supplierName',
              type: 'text',
              label: { en: 'Supplier (Wholesale)', th: 'ชื่อ Wholesale (Supplier)' },
              admin: {
                width: '33%',
                description: {
                  en: 'Wholesale supplier name — internal use only',
                  th: 'ชื่อซัพพลายเออร์ — ใช้อ้างอิงภายในเท่านั้น',
                },
              },
            },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'airlineName',
              type: 'text',
              label: { en: 'Airline', th: 'สายการบิน' },
              admin: { width: '33%' },
            },
            {
              name: 'travelDate',
              type: 'text',
              label: { en: 'Travel Dates', th: 'วันเดินทาง' },
              admin: { width: '33%' },
            },
            {
              name: 'duration',
              type: 'text',
              label: { en: 'Duration', th: 'ระยะเวลา' },
              admin: { width: '33%' },
            },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'coverImageUrl',
              type: 'text',
              label: { en: 'Cover Image URL', th: 'URL รูปปกทัวร์' },
              admin: { readOnly: true, width: '33%' },
            },
            {
              name: 'periodId',
              type: 'text',
              label: 'Period ID',
              admin: { readOnly: true, width: '33%' },
            },
            {
              name: 'interTourSlug',
              type: 'text',
              label: { en: 'InterTour Slug', th: 'Slug ของ InterTour' },
              admin: { readOnly: true, width: '33%' },
            },
          ],
        },
      ],
    },

    // ════════════════════════════════════════════════════════════
    // 3. รายการจองและสรุปราคา (Pricing & Items)
    // ════════════════════════════════════════════════════════════
    {
      type: 'collapsible',
      label: { en: '💰 Pricing & Travelers', th: '💰 รายการจองและสรุปราคา' },
      fields: [
        {
          name: 'travelers',
          type: 'json',
          label: { en: 'Traveler Breakdown', th: 'รายละเอียดผู้เดินทาง (แจกแจง)' },
          validate: (value) => {
            if (!value) return true
            if (!Array.isArray(value)) return 'ต้องเป็น array'
            for (const t of value) {
              if (!t.type || t.qty === undefined) return 'ผู้เดินทางแต่ละคนต้องมี type และ qty'
            }
            return true
          },
          admin: {
            description:
              'JSON: [{ type, label, qty, pricePerPerson, total }] e.g. Adult Twin, Child w/ Bed, Single Supplement',
          },
        },
        {
          type: 'row',
          fields: [
            {
              name: 'depositPerPerson',
              type: 'text',
              label: { en: 'Deposit per Person (THB)', th: 'เงินมัดจำ/ท่าน (บาท)' },
              admin: { width: '33%' },
            },
            {
              name: 'paymentDeadline',
              type: 'text',
              label: { en: 'Payment Deadline', th: 'ชำระมัดจำก่อนวันที่' },
              admin: { width: '33%' },
            },
            {
              name: 'totalAmount',
              type: 'number',
              label: { en: 'Grand Total (THB)', th: 'ยอดรวมสุทธิ (บาท)' },
              admin: { width: '33%' },
            },
          ],
        },
      ],
    },

    // ════════════════════════════════════════════════════════════
    // 4. รายละเอียดผู้จอง (Booker Details) — PDPA Encrypted
    // ════════════════════════════════════════════════════════════
    {
      type: 'collapsible',
      label: { en: '👤 Booker Details', th: '👤 รายละเอียดผู้จอง' },
      admin: {
        description: {
          en: 'Personal data is encrypted at database level (PDPA)',
          th: 'ข้อมูลส่วนบุคคลถูกเข้ารหัสในฐานข้อมูล (PDPA)',
        },
      },
      fields: [
        {
          type: 'row',
          fields: [
            {
              name: 'firstName',
              type: 'text',
              label: { en: 'First Name 🔒', th: 'ชื่อ 🔒' },
              required: true,
              admin: { width: '50%' },
              hooks: encryptionHooks,
            },
            {
              name: 'lastName',
              type: 'text',
              label: { en: 'Last Name 🔒', th: 'นามสกุล 🔒' },
              required: true,
              admin: { width: '50%' },
              hooks: encryptionHooks,
            },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'email',
              type: 'email',
              label: { en: 'Email', th: 'อีเมล' },
              required: true,
              admin: { width: '50%' },
            },
            {
              name: 'phone',
              type: 'text',
              label: { en: 'Phone 🔒', th: 'เบอร์โทรศัพท์ 🔒' },
              required: true,
              admin: { width: '50%' },
              hooks: encryptionHooks,
            },
          ],
        },
        {
          name: 'specialRequests',
          type: 'textarea',
          label: { en: 'Customer Remarks', th: 'หมายเหตุจากลูกค้า' },
          admin: {
            description: {
              en: 'e.g. Extra bed, vegetarian food, wheelchair',
              th: 'เช่น ขอเตียงเสริม, ทานอาหารมังสวิรัติ, รถเข็น',
            },
          },
        },
      ],
    },

    // ════════════════════════════════════════════════════════════
    // 5. รายชื่อผู้เดินทาง (Passenger Names) — Optional
    // ════════════════════════════════════════════════════════════
    {
      type: 'collapsible',
      label: { en: '🧳 Passenger Names', th: '🧳 รายชื่อผู้เดินทาง' },
      admin: {
        description: {
          en: 'Additional passenger names for insurance or wholesale submission',
          th: 'รายชื่อผู้เดินทางคนอื่นๆ สำหรับทำประกันหรือส่งให้ Wholesale',
        },
        condition: () => true, // Always show but collapsible
      },
      fields: [
        {
          name: 'passengerNames',
          type: 'array',
          label: { en: 'Passengers', th: 'รายชื่อผู้เดินทาง' },
          labels: {
            singular: { en: 'Passenger', th: 'ผู้เดินทาง' },
            plural: { en: 'Passengers', th: 'ผู้เดินทาง' },
          },
          fields: [
            {
              name: 'fullName',
              type: 'text',
              label: { en: 'Full Name', th: 'ชื่อ-นามสกุล' },
              required: true,
            },
          ],
        },
      ],
    },

    // ════════════════════════════════════════════════════════════
    // 6. หมายเหตุสำหรับ Admin (Internal Note)
    // ════════════════════════════════════════════════════════════
    {
      name: 'internalNote',
      type: 'textarea',
      label: { en: 'Internal Note', th: 'หมายเหตุสำหรับ Admin' },
      admin: {
        position: 'sidebar',
        description: {
          en: 'Internal notes — customers cannot see this',
          th: 'โน้ตภายใน — ลูกค้าไม่เห็น (เช่น "โทรหาลูกค้าแล้ว", "เช็คกับ Wholesale แล้ว")',
        },
      },
    },
  ],
  timestamps: true,
}
