import { GlobalConfig } from 'payload'
import { checkRole } from '@/utilities/checkRole'
import { hasPermission } from '@/access/isAgentStarter'
import { revalidateCompanyInfo } from './hooks/revalidateCompanyInfo'

export const CompanyInfo: GlobalConfig = {
  slug: 'company-info',
  label: { en: 'Company Info', th: 'ข้อมูลบริษัท' },
  access: {
    read: () => true,
    update: ({ req: { user } }) =>
      checkRole(['admin'], user) || hasPermission('canManageContent', user),
  },
  admin: {
    description: {
      en: 'Company info for emails, bookings and website',
      th: 'ข้อมูลบริษัทสำหรับใช้ในอีเมล, ใบจอง และหน้าเว็บ',
    },
  },
  hooks: {
    afterChange: [revalidateCompanyInfo],
  },
  fields: [
    {
      name: 'companyLogo',
      type: 'upload',
      relationTo: 'media',
      label: { en: 'Header Logo', th: 'โลโก้บริษัท (Header)' },
      admin: {
        description: {
          en: 'Logo for Header and documents (recommended PNG transparent)',
          th: 'โลโก้สำหรับแสดงใน Header และเอกสาร (แนะนำ PNG พื้นหลังใส)',
        },
      },
    },
    {
      name: 'footerLogo',
      type: 'upload',
      relationTo: 'media',
      label: { en: 'Footer Logo', th: 'โลโก้บริษัท (Footer)' },
      admin: {
        description: {
          en: 'Footer logo — uses main logo if empty',
          th: 'โลโก้สำหรับแสดงใน Footer — ถ้าไม่ใส่จะใช้ Logo หลักแทน',
        },
      },
    },
    {
      name: 'companyName',
      type: 'text',
      label: { en: 'Company Name', th: 'ชื่อบริษัท' },
      defaultValue: 'WOW Tour',
      admin: {
        description: {
          en: 'Company name in booking confirmation emails',
          th: 'ชื่อบริษัทที่จะแสดงในอีเมลยืนยันการจอง',
        },
      },
    },
    {
      name: 'companyNameEn',
      type: 'text',
      label: { en: 'Company Name (EN)', th: 'ชื่อบริษัท (EN)' },
      admin: {
        description: { en: 'Company name in English', th: 'ชื่อบริษัทภาษาอังกฤษ' },
      },
    },
    {
      name: 'tatLicense',
      type: 'text',
      label: { en: 'TAT License Number', th: 'เลขทะเบียน ททท.' },
      defaultValue: '11/123456',
      admin: {
        description: {
          en: 'TAT License Number',
          th: 'เลขที่ใบอนุญาตจากการท่องเที่ยวแห่งประเทศไทย',
        },
      },
    },
    {
      name: 'callCenter',
      type: 'text',
      label: { en: 'Call Center', th: 'เบอร์ Call Center' },
      defaultValue: '#',
      admin: {
        description: {
          en: 'Main Call Center — shown in Header, Footer, Contact',
          th: 'เบอร์ Call Center หลัก — แสดงที่ Header, Sticky Social, Footer และ Contact Us',
        },
      },
    },
    {
      name: 'hotline',
      type: 'text',
      label: { en: 'Hotline', th: 'เบอร์ Hotline' },
      defaultValue: '#',
      admin: {
        description: {
          en: 'Hotline — shown in Header info bar (hidden if empty)',
          th: 'เบอร์ Hotline แยกจาก Call Center — แสดงที่ Header info bar (ถ้าไม่ใส่จะไม่แสดง)',
        },
      },
    },
    {
      name: 'phones',
      type: 'array',
      label: { en: 'Phone', th: 'เบอร์โทรศัพท์' },
      admin: {
        description: {
          en: 'All phone numbers — shown in Footer and Contact',
          th: 'เบอร์โทรศัพท์ทั้งหมดของบริษัท — แสดงที่ Footer และ Contact Us',
        },
      },
      fields: [
        {
          type: 'row',
          fields: [
            {
              name: 'number',
              type: 'text',
              label: { en: 'Phone', th: 'เบอร์โทรศัพท์' },
              required: true,
              admin: { width: '50%', placeholder: 'เช่น 02-XXX-XXXX' },
            },
            {
              name: 'label',
              type: 'text',
              label: { en: 'Label (Optional)', th: 'ป้ายกำกับ (ไม่บังคับ)' },
              admin: { width: '50%', placeholder: 'เช่น สำนักงาน, ฝ่ายขาย' },
            },
          ],
        },
      ],
    },
    {
      name: 'email',
      type: 'text',
      label: { en: 'Company Email', th: 'อีเมลบริษัท' },
      defaultValue: '#',
      admin: { description: { en: 'e.g., info@wowtour.com', th: 'เช่น info@wowtour.com' } },
    },
    {
      name: 'bookingEmail',
      type: 'text',
      label: { en: 'Booking Email', th: 'อีเมลบริษัทสำหรับรับใบสั่งจองทัวร์' },
      admin: {
        description: { 
          en: 'Email to receive notifications for new tour bookings', 
          th: 'อีเมลสำหรับรับแจ้งเตือนเมื่อมีลูกค้าระบุจองทัวร์เข้ามา' 
        }
      },
    },
    // ---- Booking Code Format ----
    {
      type: 'collapsible',
      label: { en: '🔢 Booking Code Format', th: '🔢 รูปแบบรหัสจอง' },
      admin: {
        initCollapsed: true,
        description: {
          en: 'Configure the format of booking codes generated by the system',
          th: 'ตั้งค่ารูปแบบรหัสจองที่ระบบสร้างให้อัตโนมัติ',
        },
      },
      fields: [
        {
          type: 'row',
          fields: [
            {
              name: 'bookingPrefix',
              type: 'text',
              label: { en: 'Prefix', th: 'ตัวอักษรนำหน้า' },
              defaultValue: 'BK',
              admin: {
                width: '33%',
                placeholder: 'e.g. BK, WT, TOUR',
                description: {
                  en: '2-6 characters (e.g. BK, WT, TOUR)',
                  th: 'ตัวอักษรนำหน้า 2-6 ตัว (เช่น BK, WT, TOUR)',
                },
              },
              validate: (value: string | null | undefined) => {
                if (!value) return true
                if (value.length < 2 || value.length > 6) return 'Prefix ต้องมี 2-6 ตัวอักษร'
                if (!/^[A-Za-z0-9]+$/.test(value)) return 'Prefix ต้องเป็นตัวอักษรภาษาอังกฤษหรือตัวเลขเท่านั้น'
                return true
              },
            },
            {
              name: 'bookingSeparator',
              type: 'select',
              label: { en: 'Separator', th: 'ตัวคั่น' },
              defaultValue: '-',
              options: [
                { label: '- (Dash)', value: '-' },
                { label: '. (Dot)', value: '.' },
                { label: '_ (Underscore)', value: '_' },
              ],
              admin: {
                width: '33%',
                description: {
                  en: 'Character between each part',
                  th: 'ตัวคั่นระหว่างแต่ละส่วน',
                },
              },
            },
            {
              name: 'bookingDigits',
              type: 'select',
              label: { en: 'Running Number Digits', th: 'จำนวนหลักเลข Running' },
              defaultValue: '4',
              options: [
                { label: '3 digits (001)', value: '3' },
                { label: '4 digits (0001)', value: '4' },
                { label: '5 digits (00001)', value: '5' },
              ],
              admin: {
                width: '33%',
                description: {
                  en: 'Number of digits for running number',
                  th: 'จำนวนหลักของเลข Running Number',
                },
              },
            },
          ],
        },
        {
          name: 'bookingCodePreview',
          type: 'ui',
          admin: {
            components: {
              Field: '@/globals/CompanyInfo/components/BookingCodePreview',
            },
          },
        },
      ],
    },
    {
      name: 'address',
      type: 'textarea',
      label: { en: 'Company Address', th: 'ที่อยู่บริษัท' },
      defaultValue: '589/98 อาคารชุดทาวเวอร์ 1 ออฟฟิศ ชั้นที่ 18 ถนน เทพรัตน\nแขวงบางนาเหนือ เขตบางนา กรุงเทพมหานคร 10260',
      admin: {
        description: { en: 'Full address for documents', th: 'ที่อยู่เต็มสำหรับแสดงในเอกสาร' },
      },
    },
    {
      name: 'website',
      type: 'text',
      label: { en: 'Website', th: 'เว็บไซต์' },
      defaultValue: '#',
      admin: {
        description: {
          en: 'Website URL, e.g., https://wowtour.com',
          th: 'URL เว็บไซต์หลัก เช่น https://wowtour.com',
        },
      },
    },
    {
      name: 'lineOA',
      type: 'text',
      label: 'LINE Official Account',
      defaultValue: '#',
      admin: {
        description: { en: 'LINE ID e.g., @wowtour', th: 'LINE ID เช่น @wowtour' },
      },
    },
    {
      name: 'lineLink',
      type: 'text',
      label: 'LINE Link (URL)',
      defaultValue: '#',
      admin: {
        description: {
          en: 'LINE OA URL (makes text clickable)',
          th: 'URL ของ LINE OA เช่น https://lin.me/ti/p/... (ใช้ทำให้ข้อความเป็นลิงก์สามารถคลิกได้)',
        },
      },
    },
    {
      name: 'qrCode',
      type: 'upload',
      relationTo: 'media',
      label: 'QR Code (LINE/Facebook)',
      admin: {
        description: {
          en: 'QR Code for LINE, Facebook, etc.',
          th: 'อัพโหลดรูป QR Code เช่น LINE QR, เพจ Facebook ฯลฯ',
        },
      },
    },
    {
      name: 'businessHours',
      type: 'text',
      label: { en: 'Business Hours', th: 'เวลาทำการ' },
      defaultValue: '09:00 - 17:00 น.',
      admin: {
        description: {
          en: 'Working hours, e.g., Mon-Fri 09:00-17:00',
          th: 'เวลาทำการ เช่น จันทร์-ศุกร์ 09:00 - 17:00 น.',
        },
      },
    },
    {
      name: 'socialLinks',
      type: 'array',
      label: 'Social Media Links',
      admin: {
        description: {
          en: 'Social Media links — used in Footer, Sticky Social',
          th: 'ลิงก์ Social Media หลักของบริษัท — ใช้ร่วมกันใน Footer, Sticky Social',
        },
      },
      fields: [
        {
          type: 'row',
          fields: [
            {
              name: 'platform',
              type: 'select',
              label: 'Platform',
              required: true,
              options: [
                { label: 'Facebook', value: 'facebook' },
                { label: 'LINE', value: 'line' },
                { label: 'Instagram', value: 'instagram' },
                { label: 'TikTok', value: 'tiktok' },
                { label: 'YouTube', value: 'youtube' },
                { label: 'Twitter / X', value: 'twitter' },
                { label: 'Email', value: 'email' },
                { label: 'Phone', value: 'phone' },
                { label: 'Website', value: 'website' },
                { label: 'WhatsApp', value: 'whatsapp' },
              ],
              admin: { width: '25%' },
            },
            {
              name: 'url',
              type: 'text',
              label: { en: 'URL / / Email', th: 'URL / เบอร์โทร / Email' },
              required: true,
              admin: {
                width: '45%',
                placeholder: 'https://...',
              },
            },
            {
              name: 'label',
              type: 'text',
              label: 'Label',
              admin: {
                width: '30%',
                placeholder: 'ข้อความแสดง',
              },
            },
          ],
        },
        {
          type: 'row',
          admin: {
            style: { paddingTop: 0, marginTop: '-8px' },
          },
          fields: [
            {
              name: 'showInHeader',
              type: 'checkbox',
              label: { en: 'Header', th: 'เปิดใช้งาน Header' },
              defaultValue: true,
            },
            {
              name: 'showInFooter',
              type: 'checkbox',
              label: { en: 'Footer', th: 'เปิดใช้งาน Footer' },
              defaultValue: true,
            },
            {
              name: 'showInSticky',
              type: 'checkbox',
              label: { en: 'Sticky Social', th: 'เปิดใช้งาน Sticky Social' },
              defaultValue: true,
            },
          ],
        },
      ],
    },
    {
      name: 'trustBadges',
      type: 'upload',
      relationTo: 'media',
      label: 'Trust Badges',
      admin: {
        description: {
          en: 'Trust Badges (VISA, Mastercard, ATTA, etc.) — recommended PNG transparent',
          th: 'รูป Trust Badges (VISA, Mastercard, ATTA, TAT, DBD Verified ฯลฯ) แนะนำใช้ PNG พื้นหลังใส',
        },
      },
    },
  ],
}
